# Generated by Django 2.0.4 on 2018-05-08 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_time',
            new_name='创建时间',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='文章分类',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='excerpt',
            new_name='文章摘要（必填项）',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='文章标签',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='modified_time',
            new_name='最后修改时间',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='标题',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='正文',
        ),
    ]
