# Generated by Django 2.0.4 on 2018-05-08 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180508_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='正文',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='文章分类',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='创建时间',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='文章摘要（必填项）',
            new_name='excerpt',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='最后修改时间',
            new_name='modified_time',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='文章标签',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='标题',
            new_name='title',
        ),
    ]
