# Generated by Django 2.0.4 on 2018-05-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180522_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_url', models.ImageField(blank=True, max_length=200, null=True, upload_to='image')),
            ],
            options={
                'db_table': 'media_test',
            },
        ),
    ]
