# Generated by Django 2.0.4 on 2018-06-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_mediatest'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediatest',
            name='name_meida',
            field=models.CharField(default='', max_length=100, verbose_name='图片名称'),
        ),
    ]
